# Generated by Django 5.0.2 on 2024-02-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_productos_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='categoria',
        ),
    ]
