# Generated by Django 5.0.2 on 2024-02-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_precio_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=40),
        ),
    ]
