# Generated by Django 5.0.2 on 2024-02-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_productos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(max_length=100)),
                ('caro', models.BooleanField(default=False)),
                ('barato', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Descuentos',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
