# Generated by Django 5.0.2 on 2024-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_remove_descuentos_entregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='Tiendas',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='productos_desc',
            field=models.CharField(max_length=40),
        ),
    ]
