# Generated by Django 5.0.2 on 2024-02-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_descuentos_tiendas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentos',
            old_name='Tiendas',
            new_name='tiendas',
        ),
    ]
